<header class="header">
    <div class="logo-agsoftware">
        <img src="{{media url=wysiwyg/nuevo-logo_1.png}}" alt="" />
    </div>
    <nav class="navegacion">
        <ul class="lista">
            <li><a href="/home">Inicio<span></span></a></li>
            <li><a href="">¿Que ofrecemos?<span></span></a>
                <div class="submenu">
                    <div class="submenu-items acer-servicio">
                        <p class="subtittle">Acerca de y servicios</p>
                        <ul>
                            <li><a href="">Acerca de la agencia</a></li>
                            <li><a href="">Acerca de la apuesta en marcha</a></li>
                            <li><a href="">Agencia de servicio</a></li>
                            <li><a href="">Apuesta en marcha de servicio</a></li>
                        </ul>
                    </div>
                    <div class="linea"></div>
                    <div class="submenu-items car">
                        <p class="subtittle">Carreras</p>
                        <ul>
                            <li><a href="">Carreras</a></li>
                            <li><a href="">Carreras soltero</a></li>
                            <li><a href="">Contratanos</a></li>
                            
                        </ul>
                    </div>
                    <div class="linea"></div>
                    <div class="submenu-items carre">
                        <p class="subtittle">Ingresar Registrar</p>
                        <ul>
                            <li><a href="">Iniciar sesión simple</a></li>
                            <li><a href="">Registrarse simple</a></li>
                            <li><a href="">Recuperar cuenta</a></li>                          
                        </ul>
                    </div>
                    <div class="linea"></div>
                    <div class="submenu-items carre">
                        <p class="subtittle">Contactenos</p>
                        <ul>
                            <li><a href="">Agencia de contactos</a></li>
                            <li><a href="">Contactos de negocios</a></li>                           
                        </ul>
                    </div>
                    <div class="linea"></div>
                    <div class="submenu-items carre">
                        <p class="subtittle">Utilidades</p>
                        <ul>
                            <li><a href="">Ayudar</a></li>
                            <li><a href="">Precio</a></li>
                            <li><a href="">Terminos y condiciones</a></li>
                            <li><a href="">Politica de privacidad</a></li>
                        </ul>
                    </div>
                    <div class="linea"></div>
                    <div class="submenu-items especi">
                        <p class="subtittle">Especialidades</p>
                        <ul>
                            <li><a href="">Prócimamente en breve pronto</a></li>
                            <li><a href="">Modo de mantenimiento</a></li>
                            <li><a href="">error 404</a></li>                      
                        </ul>
                    </div>

                </div>
            </li>               
            <li><a href="/equipo">Nuestro Equipo?</a></li>
            <li><a href="/contactenos">Contactenos?</a></li>     

        </ul>
    </nav>
</header>
